---
permissions:
  contents: write
name: Build
on:
  push:
    branches:
      - 'develop'

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install modules
        run: yarn install
      - name: Run ESLint
        run: yarn run lint
  build-dist:
    needs: eslint-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install modules
        run: yarn install
      - name: Install build config
        run: |
          cat << EOF > config/local_config.yaml
            host: 0.0.0.0
            port: 8088
            server: http://localhost:8888

            theme: custom

            globalVariables:
              websocketEndpoint: wss://api.dev.core.resetdata.com/api/billing/wss
              defaultLanguage: en
              supportLanguages: # use value in i18n.js
                - en
          EOF

      - name: Build dist
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: static-release
          path: |
            skyline_console/static
            Dockerfile
...
