---
name: Docker build-push
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [develop]
env:
  ARTIFACT_FOLDER: static-release
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_FOLDER }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GHE_ARTIFACT_PAT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HARBOR_ROBOT_USER }}
          password: ${{ secrets.HARBOR_ROBOT_PASS }}
          registry: harbor.core.resetdata.com
      - 
        name: Push docker image to Harbor
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.ARTIFACT_FOLDER }}"
          push: true
          tags: harbor.core.resetdata.com/dashboard/frontend:${{ github.sha }}

...
